/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  ChecklistItems: () => import('#controllers/checklist_items_controller'),
  CleaningReviews: () => import('#controllers/cleaning_reviews_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Employees: () => import('#controllers/employees_controller'),
  Housings: () => import('#controllers/housings_controller'),
  PublicReviews: () => import('#controllers/public_reviews_controller'),
  Reservations: () => import('#controllers/reservations_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
