/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CleaningReviewTransformer from '#transformers/cleaning_review_transformer'
import type EmployeeTransformer from '#transformers/employee_transformer'
import type HousingTransformer from '#transformers/housing_transformer'
import type ReservationTransformer from '#transformers/reservation_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type ChecklistItemTransformer from '#transformers/checklist_item_transformer'

export namespace Data {
  export type CleaningReview = InferData<CleaningReviewTransformer>
  export namespace CleaningReview {
    export type Variants = InferVariants<CleaningReviewTransformer>
  }
  export type Employee = InferData<EmployeeTransformer>
  export namespace Employee {
    export type Variants = InferVariants<EmployeeTransformer>
  }
  export type Housing = InferData<HousingTransformer>
  export namespace Housing {
    export type Variants = InferVariants<HousingTransformer>
  }
  export type Reservation = InferData<ReservationTransformer>
  export namespace Reservation {
    export type Variants = InferVariants<ReservationTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type ChecklistItem = InferData<ChecklistItemTransformer>
  export namespace ChecklistItem {
    export type Variants = InferVariants<ChecklistItemTransformer>
  }
}
