/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type HousingTransformer from '#transformers/housing_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Housing = InferData<HousingTransformer>
  export namespace Housing {
    export type Variants = InferVariants<HousingTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
