/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ChecklistItemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'label', 'position', 'updatedAt', 'userId'] as const
  $columns = ChecklistItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class CleaningReviewSchema extends BaseModel {
  static $columns = ['additionnalInfos', 'aiOutput', 'assignedEmployeeId', 'createdAt', 'id', 'localVideoPath', 'mimeType', 'reservationId', 'status', 'updatedAt', 'uri', 'voiceMessageFile'] as const
  $columns = CleaningReviewSchema.$columns
  @column()
  declare additionnalInfos: string | null
  @column()
  declare aiOutput: any | null
  @column()
  declare assignedEmployeeId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare localVideoPath: string | null
  @column()
  declare mimeType: string | null
  @column()
  declare reservationId: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uri: string | null
  @column()
  declare voiceMessageFile: string | null
}

export class EmployeeSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'fullName', 'gender', 'id', 'tel', 'updatedAt', 'userId'] as const
  $columns = EmployeeSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare fullName: string
  @column()
  declare gender: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tel: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class HousingSchema extends BaseModel {
  static $columns = ['address', 'capacity', 'createdAt', 'id', 'name', 'type', 'updatedAt', 'userId'] as const
  $columns = HousingSchema.$columns
  @column()
  declare address: string
  @column()
  declare capacity: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ReservationSchema extends BaseModel {
  static $columns = ['createdAt', 'housingId', 'id', 'moveInDate', 'moveOutDate', 'numberOfAdult', 'numberOfBaby', 'numberOfChild', 'specialInfos', 'updatedAt'] as const
  $columns = ReservationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare housingId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare moveInDate: DateTime
  @column.dateTime()
  declare moveOutDate: DateTime
  @column()
  declare numberOfAdult: number
  @column()
  declare numberOfBaby: number
  @column()
  declare numberOfChild: number
  @column()
  declare specialInfos: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'emailVerificationCode', 'emailVerificationCodeExpiresAt', 'emailVerified', 'emailVerifiedAt', 'firstName', 'id', 'lastName', 'password', 'resetPasswordToken', 'resetPasswordTokenExpiresAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare emailVerificationCode: string | null
  @column.dateTime()
  declare emailVerificationCodeExpiresAt: DateTime | null
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare resetPasswordToken: string | null
  @column.dateTime()
  declare resetPasswordTokenExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
